[Build]
builder = "dockerfile"
dockerfilePath = "./JalemosBackend/JalemosBackend/Dockerfile"

[Deploy]
startCommand = "dotnet JalemosBackend.dll"
restartPolicyType = "always"
healthcheckPath = "/health"