// Vehicle makes, models, and year range for the driver registration dropdown pickers.
// Generated by Claude Sonnet 4.6 — curated for the Costa Rican market.

export const VEHICLE_MAKES = [
  'Chevrolet',
  'Ford',
  'Honda',
  'Hyundai',
  'Isuzu',
  'Kia',
  'Mazda',
  'Mercedes-Benz',
  'Mitsubishi',
  'Nissan',
  'Renault',
  'Subaru',
  'Suzuki',
  'Toyota',
  'Volkswagen',
] as const;

export const VEHICLE_MODELS: Record<string, string[]> = {
  Chevrolet: ['Aveo', 'Captiva', 'Colorado', 'Groove', 'Spark', 'Tracker', 'Trax'],
  Ford:      ['Ecosport', 'Escape', 'Explorer', 'Maverick', 'Mustang', 'Ranger', 'Territory'],
  Honda:     ['Accord', 'City', 'Civic', 'CR-V', 'Fit', 'HR-V', 'Passport', 'Pilot', 'Ridgeline'],
  Hyundai:   ['Accent', 'Creta', 'Elantra', 'Grand i10', 'i10', 'Ioniq 5', 'Santa Fe', 'Tucson'],
  Isuzu:     ['D-Max', 'MU-X'],
  Kia:       ['Carnival', 'Cerato', 'EV6', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Sportage', 'Stinger'],
  Mazda:     ['BT-50', 'CX-30', 'CX-5', 'CX-9', 'Mazda 2', 'Mazda 3', 'Mazda 6'],
  'Mercedes-Benz': ['A 180', 'C 200', 'C 300', 'E 300', 'GLA 200', 'GLC 300', 'GLE 350'],
  Mitsubishi:['ASX', 'Eclipse Cross', 'L200', 'Montero', 'Montero Sport', 'Outlander'],
  Nissan:    ['Frontier', 'Kicks', 'March', 'Murano', 'Pathfinder', 'Sentra', 'Versa', 'X-Trail'],
  Renault:   ['Duster', 'Kwid', 'Logan', 'Oroch', 'Sandero', 'Stepway'],
  Subaru:    ['Forester', 'Impreza', 'Legacy', 'Outback', 'XV'],
  Suzuki:    ['Baleno', 'Fronx', 'Grand Vitara', 'Jimny', 'S-Presso', 'Swift', 'SX4', 'Vitara'],
  Toyota:    ['Avanza', 'Camry', 'Corolla', 'Fortuner', 'GR86', 'Hilux', 'Land Cruiser', 'Prado', 'RAV4', 'Rush', 'Yaris'],
  Volkswagen:['Golf', 'Polo', 'T-Cross', 'Taos', 'Tiguan', 'Touareg', 'Vento'],
};

const currentYear = new Date().getFullYear();
export const VEHICLE_YEARS: string[] = Array.from(
  { length: currentYear - 1989 },
  (_, i) => String(currentYear - i)
);
